// This file is auto-generated by generate-static-routes.js
// Do not edit this file manually.

import * as route0 from '../src/app/api/__create/check-social-secrets/route.js';
import * as route1 from '../src/app/api/auth/expo-web-success/route.js';
import * as route2 from '../src/app/api/competitors/analyze/route.js';
import * as route3 from '../src/app/api/campaigns/generate/route.js';
import * as route4 from '../src/app/api/competitors/delete/route.js';
import * as route5 from '../src/app/api/creatives/generate/route.js';
import * as route6 from '../src/app/api/brand/upload-logo/route.js';
import * as route7 from '../src/app/api/businesses/create/route.js';
import * as route8 from '../src/app/api/utils/keys-status/route.js';
import * as route9 from '../src/app/api/videos/regenerate/route.js';
import * as route10 from '../src/app/api/__create/ssr-test/route.js';
import * as route11 from '../src/app/api/campaigns/delete/route.js';
import * as route12 from '../src/app/api/competitors/list/route.js';
import * as route13 from '../src/app/api/content/generate/route.js';
import * as route14 from '../src/app/api/creatives/delete/route.js';
import * as route15 from '../src/app/api/businesses/list/route.js';
import * as route16 from '../src/app/api/businesses/[id]/route.js';
import * as route17 from '../src/app/api/videos/generate/route.js';
import * as route18 from '../src/app/api/brand/generate/route.js';
import * as route19 from '../src/app/api/campaigns/list/route.js';
import * as route20 from '../src/app/api/content/delete/route.js';
import * as route21 from '../src/app/api/creatives/list/route.js';
import * as route22 from '../src/app/api/scrape/website/route.js';
import * as route23 from '../src/app/api/videos/create/route.js';
import * as route24 from '../src/app/api/videos/delete/route.js';
import * as route25 from '../src/app/api/brand/delete/route.js';
import * as route26 from '../src/app/api/content/list/route.js';
import * as route27 from '../src/app/api/videos/list/route.js';
import * as route28 from '../src/app/api/auth/token/route.js';
import * as route29 from '../src/app/api/brand/get/route.js';

export function registerStaticRoutes(api: any) {
  if ((route0 as any).GET) {
    api.get('/__create/check-social-secrets', async (c: any) => {
      const params = c.req.param();
      return await (route0 as any).GET(c.req.raw, { params });
    });
  }
  if ((route0 as any).POST) {
    api.post('/__create/check-social-secrets', async (c: any) => {
      const params = c.req.param();
      return await (route0 as any).POST(c.req.raw, { params });
    });
  }
  if ((route0 as any).PUT) {
    api.put('/__create/check-social-secrets', async (c: any) => {
      const params = c.req.param();
      return await (route0 as any).PUT(c.req.raw, { params });
    });
  }
  if ((route0 as any).DELETE) {
    api.delete('/__create/check-social-secrets', async (c: any) => {
      const params = c.req.param();
      return await (route0 as any).DELETE(c.req.raw, { params });
    });
  }
  if ((route0 as any).PATCH) {
    api.patch('/__create/check-social-secrets', async (c: any) => {
      const params = c.req.param();
      return await (route0 as any).PATCH(c.req.raw, { params });
    });
  }
  if ((route1 as any).GET) {
    api.get('/auth/expo-web-success', async (c: any) => {
      const params = c.req.param();
      return await (route1 as any).GET(c.req.raw, { params });
    });
  }
  if ((route1 as any).POST) {
    api.post('/auth/expo-web-success', async (c: any) => {
      const params = c.req.param();
      return await (route1 as any).POST(c.req.raw, { params });
    });
  }
  if ((route1 as any).PUT) {
    api.put('/auth/expo-web-success', async (c: any) => {
      const params = c.req.param();
      return await (route1 as any).PUT(c.req.raw, { params });
    });
  }
  if ((route1 as any).DELETE) {
    api.delete('/auth/expo-web-success', async (c: any) => {
      const params = c.req.param();
      return await (route1 as any).DELETE(c.req.raw, { params });
    });
  }
  if ((route1 as any).PATCH) {
    api.patch('/auth/expo-web-success', async (c: any) => {
      const params = c.req.param();
      return await (route1 as any).PATCH(c.req.raw, { params });
    });
  }
  if ((route2 as any).GET) {
    api.get('/competitors/analyze', async (c: any) => {
      const params = c.req.param();
      return await (route2 as any).GET(c.req.raw, { params });
    });
  }
  if ((route2 as any).POST) {
    api.post('/competitors/analyze', async (c: any) => {
      const params = c.req.param();
      return await (route2 as any).POST(c.req.raw, { params });
    });
  }
  if ((route2 as any).PUT) {
    api.put('/competitors/analyze', async (c: any) => {
      const params = c.req.param();
      return await (route2 as any).PUT(c.req.raw, { params });
    });
  }
  if ((route2 as any).DELETE) {
    api.delete('/competitors/analyze', async (c: any) => {
      const params = c.req.param();
      return await (route2 as any).DELETE(c.req.raw, { params });
    });
  }
  if ((route2 as any).PATCH) {
    api.patch('/competitors/analyze', async (c: any) => {
      const params = c.req.param();
      return await (route2 as any).PATCH(c.req.raw, { params });
    });
  }
  if ((route3 as any).GET) {
    api.get('/campaigns/generate', async (c: any) => {
      const params = c.req.param();
      return await (route3 as any).GET(c.req.raw, { params });
    });
  }
  if ((route3 as any).POST) {
    api.post('/campaigns/generate', async (c: any) => {
      const params = c.req.param();
      return await (route3 as any).POST(c.req.raw, { params });
    });
  }
  if ((route3 as any).PUT) {
    api.put('/campaigns/generate', async (c: any) => {
      const params = c.req.param();
      return await (route3 as any).PUT(c.req.raw, { params });
    });
  }
  if ((route3 as any).DELETE) {
    api.delete('/campaigns/generate', async (c: any) => {
      const params = c.req.param();
      return await (route3 as any).DELETE(c.req.raw, { params });
    });
  }
  if ((route3 as any).PATCH) {
    api.patch('/campaigns/generate', async (c: any) => {
      const params = c.req.param();
      return await (route3 as any).PATCH(c.req.raw, { params });
    });
  }
  if ((route4 as any).GET) {
    api.get('/competitors/delete', async (c: any) => {
      const params = c.req.param();
      return await (route4 as any).GET(c.req.raw, { params });
    });
  }
  if ((route4 as any).POST) {
    api.post('/competitors/delete', async (c: any) => {
      const params = c.req.param();
      return await (route4 as any).POST(c.req.raw, { params });
    });
  }
  if ((route4 as any).PUT) {
    api.put('/competitors/delete', async (c: any) => {
      const params = c.req.param();
      return await (route4 as any).PUT(c.req.raw, { params });
    });
  }
  if ((route4 as any).DELETE) {
    api.delete('/competitors/delete', async (c: any) => {
      const params = c.req.param();
      return await (route4 as any).DELETE(c.req.raw, { params });
    });
  }
  if ((route4 as any).PATCH) {
    api.patch('/competitors/delete', async (c: any) => {
      const params = c.req.param();
      return await (route4 as any).PATCH(c.req.raw, { params });
    });
  }
  if ((route5 as any).GET) {
    api.get('/creatives/generate', async (c: any) => {
      const params = c.req.param();
      return await (route5 as any).GET(c.req.raw, { params });
    });
  }
  if ((route5 as any).POST) {
    api.post('/creatives/generate', async (c: any) => {
      const params = c.req.param();
      return await (route5 as any).POST(c.req.raw, { params });
    });
  }
  if ((route5 as any).PUT) {
    api.put('/creatives/generate', async (c: any) => {
      const params = c.req.param();
      return await (route5 as any).PUT(c.req.raw, { params });
    });
  }
  if ((route5 as any).DELETE) {
    api.delete('/creatives/generate', async (c: any) => {
      const params = c.req.param();
      return await (route5 as any).DELETE(c.req.raw, { params });
    });
  }
  if ((route5 as any).PATCH) {
    api.patch('/creatives/generate', async (c: any) => {
      const params = c.req.param();
      return await (route5 as any).PATCH(c.req.raw, { params });
    });
  }
  if ((route6 as any).GET) {
    api.get('/brand/upload-logo', async (c: any) => {
      const params = c.req.param();
      return await (route6 as any).GET(c.req.raw, { params });
    });
  }
  if ((route6 as any).POST) {
    api.post('/brand/upload-logo', async (c: any) => {
      const params = c.req.param();
      return await (route6 as any).POST(c.req.raw, { params });
    });
  }
  if ((route6 as any).PUT) {
    api.put('/brand/upload-logo', async (c: any) => {
      const params = c.req.param();
      return await (route6 as any).PUT(c.req.raw, { params });
    });
  }
  if ((route6 as any).DELETE) {
    api.delete('/brand/upload-logo', async (c: any) => {
      const params = c.req.param();
      return await (route6 as any).DELETE(c.req.raw, { params });
    });
  }
  if ((route6 as any).PATCH) {
    api.patch('/brand/upload-logo', async (c: any) => {
      const params = c.req.param();
      return await (route6 as any).PATCH(c.req.raw, { params });
    });
  }
  if ((route7 as any).GET) {
    api.get('/businesses/create', async (c: any) => {
      const params = c.req.param();
      return await (route7 as any).GET(c.req.raw, { params });
    });
  }
  if ((route7 as any).POST) {
    api.post('/businesses/create', async (c: any) => {
      const params = c.req.param();
      return await (route7 as any).POST(c.req.raw, { params });
    });
  }
  if ((route7 as any).PUT) {
    api.put('/businesses/create', async (c: any) => {
      const params = c.req.param();
      return await (route7 as any).PUT(c.req.raw, { params });
    });
  }
  if ((route7 as any).DELETE) {
    api.delete('/businesses/create', async (c: any) => {
      const params = c.req.param();
      return await (route7 as any).DELETE(c.req.raw, { params });
    });
  }
  if ((route7 as any).PATCH) {
    api.patch('/businesses/create', async (c: any) => {
      const params = c.req.param();
      return await (route7 as any).PATCH(c.req.raw, { params });
    });
  }
  if ((route8 as any).GET) {
    api.get('/utils/keys-status', async (c: any) => {
      const params = c.req.param();
      return await (route8 as any).GET(c.req.raw, { params });
    });
  }
  if ((route8 as any).POST) {
    api.post('/utils/keys-status', async (c: any) => {
      const params = c.req.param();
      return await (route8 as any).POST(c.req.raw, { params });
    });
  }
  if ((route8 as any).PUT) {
    api.put('/utils/keys-status', async (c: any) => {
      const params = c.req.param();
      return await (route8 as any).PUT(c.req.raw, { params });
    });
  }
  if ((route8 as any).DELETE) {
    api.delete('/utils/keys-status', async (c: any) => {
      const params = c.req.param();
      return await (route8 as any).DELETE(c.req.raw, { params });
    });
  }
  if ((route8 as any).PATCH) {
    api.patch('/utils/keys-status', async (c: any) => {
      const params = c.req.param();
      return await (route8 as any).PATCH(c.req.raw, { params });
    });
  }
  if ((route9 as any).GET) {
    api.get('/videos/regenerate', async (c: any) => {
      const params = c.req.param();
      return await (route9 as any).GET(c.req.raw, { params });
    });
  }
  if ((route9 as any).POST) {
    api.post('/videos/regenerate', async (c: any) => {
      const params = c.req.param();
      return await (route9 as any).POST(c.req.raw, { params });
    });
  }
  if ((route9 as any).PUT) {
    api.put('/videos/regenerate', async (c: any) => {
      const params = c.req.param();
      return await (route9 as any).PUT(c.req.raw, { params });
    });
  }
  if ((route9 as any).DELETE) {
    api.delete('/videos/regenerate', async (c: any) => {
      const params = c.req.param();
      return await (route9 as any).DELETE(c.req.raw, { params });
    });
  }
  if ((route9 as any).PATCH) {
    api.patch('/videos/regenerate', async (c: any) => {
      const params = c.req.param();
      return await (route9 as any).PATCH(c.req.raw, { params });
    });
  }
  if ((route10 as any).GET) {
    api.get('/__create/ssr-test', async (c: any) => {
      const params = c.req.param();
      return await (route10 as any).GET(c.req.raw, { params });
    });
  }
  if ((route10 as any).POST) {
    api.post('/__create/ssr-test', async (c: any) => {
      const params = c.req.param();
      return await (route10 as any).POST(c.req.raw, { params });
    });
  }
  if ((route10 as any).PUT) {
    api.put('/__create/ssr-test', async (c: any) => {
      const params = c.req.param();
      return await (route10 as any).PUT(c.req.raw, { params });
    });
  }
  if ((route10 as any).DELETE) {
    api.delete('/__create/ssr-test', async (c: any) => {
      const params = c.req.param();
      return await (route10 as any).DELETE(c.req.raw, { params });
    });
  }
  if ((route10 as any).PATCH) {
    api.patch('/__create/ssr-test', async (c: any) => {
      const params = c.req.param();
      return await (route10 as any).PATCH(c.req.raw, { params });
    });
  }
  if ((route11 as any).GET) {
    api.get('/campaigns/delete', async (c: any) => {
      const params = c.req.param();
      return await (route11 as any).GET(c.req.raw, { params });
    });
  }
  if ((route11 as any).POST) {
    api.post('/campaigns/delete', async (c: any) => {
      const params = c.req.param();
      return await (route11 as any).POST(c.req.raw, { params });
    });
  }
  if ((route11 as any).PUT) {
    api.put('/campaigns/delete', async (c: any) => {
      const params = c.req.param();
      return await (route11 as any).PUT(c.req.raw, { params });
    });
  }
  if ((route11 as any).DELETE) {
    api.delete('/campaigns/delete', async (c: any) => {
      const params = c.req.param();
      return await (route11 as any).DELETE(c.req.raw, { params });
    });
  }
  if ((route11 as any).PATCH) {
    api.patch('/campaigns/delete', async (c: any) => {
      const params = c.req.param();
      return await (route11 as any).PATCH(c.req.raw, { params });
    });
  }
  if ((route12 as any).GET) {
    api.get('/competitors/list', async (c: any) => {
      const params = c.req.param();
      return await (route12 as any).GET(c.req.raw, { params });
    });
  }
  if ((route12 as any).POST) {
    api.post('/competitors/list', async (c: any) => {
      const params = c.req.param();
      return await (route12 as any).POST(c.req.raw, { params });
    });
  }
  if ((route12 as any).PUT) {
    api.put('/competitors/list', async (c: any) => {
      const params = c.req.param();
      return await (route12 as any).PUT(c.req.raw, { params });
    });
  }
  if ((route12 as any).DELETE) {
    api.delete('/competitors/list', async (c: any) => {
      const params = c.req.param();
      return await (route12 as any).DELETE(c.req.raw, { params });
    });
  }
  if ((route12 as any).PATCH) {
    api.patch('/competitors/list', async (c: any) => {
      const params = c.req.param();
      return await (route12 as any).PATCH(c.req.raw, { params });
    });
  }
  if ((route13 as any).GET) {
    api.get('/content/generate', async (c: any) => {
      const params = c.req.param();
      return await (route13 as any).GET(c.req.raw, { params });
    });
  }
  if ((route13 as any).POST) {
    api.post('/content/generate', async (c: any) => {
      const params = c.req.param();
      return await (route13 as any).POST(c.req.raw, { params });
    });
  }
  if ((route13 as any).PUT) {
    api.put('/content/generate', async (c: any) => {
      const params = c.req.param();
      return await (route13 as any).PUT(c.req.raw, { params });
    });
  }
  if ((route13 as any).DELETE) {
    api.delete('/content/generate', async (c: any) => {
      const params = c.req.param();
      return await (route13 as any).DELETE(c.req.raw, { params });
    });
  }
  if ((route13 as any).PATCH) {
    api.patch('/content/generate', async (c: any) => {
      const params = c.req.param();
      return await (route13 as any).PATCH(c.req.raw, { params });
    });
  }
  if ((route14 as any).GET) {
    api.get('/creatives/delete', async (c: any) => {
      const params = c.req.param();
      return await (route14 as any).GET(c.req.raw, { params });
    });
  }
  if ((route14 as any).POST) {
    api.post('/creatives/delete', async (c: any) => {
      const params = c.req.param();
      return await (route14 as any).POST(c.req.raw, { params });
    });
  }
  if ((route14 as any).PUT) {
    api.put('/creatives/delete', async (c: any) => {
      const params = c.req.param();
      return await (route14 as any).PUT(c.req.raw, { params });
    });
  }
  if ((route14 as any).DELETE) {
    api.delete('/creatives/delete', async (c: any) => {
      const params = c.req.param();
      return await (route14 as any).DELETE(c.req.raw, { params });
    });
  }
  if ((route14 as any).PATCH) {
    api.patch('/creatives/delete', async (c: any) => {
      const params = c.req.param();
      return await (route14 as any).PATCH(c.req.raw, { params });
    });
  }
  if ((route15 as any).GET) {
    api.get('/businesses/list', async (c: any) => {
      const params = c.req.param();
      return await (route15 as any).GET(c.req.raw, { params });
    });
  }
  if ((route15 as any).POST) {
    api.post('/businesses/list', async (c: any) => {
      const params = c.req.param();
      return await (route15 as any).POST(c.req.raw, { params });
    });
  }
  if ((route15 as any).PUT) {
    api.put('/businesses/list', async (c: any) => {
      const params = c.req.param();
      return await (route15 as any).PUT(c.req.raw, { params });
    });
  }
  if ((route15 as any).DELETE) {
    api.delete('/businesses/list', async (c: any) => {
      const params = c.req.param();
      return await (route15 as any).DELETE(c.req.raw, { params });
    });
  }
  if ((route15 as any).PATCH) {
    api.patch('/businesses/list', async (c: any) => {
      const params = c.req.param();
      return await (route15 as any).PATCH(c.req.raw, { params });
    });
  }
  if ((route16 as any).GET) {
    api.get('/businesses/:id', async (c: any) => {
      const params = c.req.param();
      return await (route16 as any).GET(c.req.raw, { params });
    });
  }
  if ((route16 as any).POST) {
    api.post('/businesses/:id', async (c: any) => {
      const params = c.req.param();
      return await (route16 as any).POST(c.req.raw, { params });
    });
  }
  if ((route16 as any).PUT) {
    api.put('/businesses/:id', async (c: any) => {
      const params = c.req.param();
      return await (route16 as any).PUT(c.req.raw, { params });
    });
  }
  if ((route16 as any).DELETE) {
    api.delete('/businesses/:id', async (c: any) => {
      const params = c.req.param();
      return await (route16 as any).DELETE(c.req.raw, { params });
    });
  }
  if ((route16 as any).PATCH) {
    api.patch('/businesses/:id', async (c: any) => {
      const params = c.req.param();
      return await (route16 as any).PATCH(c.req.raw, { params });
    });
  }
  if ((route17 as any).GET) {
    api.get('/videos/generate', async (c: any) => {
      const params = c.req.param();
      return await (route17 as any).GET(c.req.raw, { params });
    });
  }
  if ((route17 as any).POST) {
    api.post('/videos/generate', async (c: any) => {
      const params = c.req.param();
      return await (route17 as any).POST(c.req.raw, { params });
    });
  }
  if ((route17 as any).PUT) {
    api.put('/videos/generate', async (c: any) => {
      const params = c.req.param();
      return await (route17 as any).PUT(c.req.raw, { params });
    });
  }
  if ((route17 as any).DELETE) {
    api.delete('/videos/generate', async (c: any) => {
      const params = c.req.param();
      return await (route17 as any).DELETE(c.req.raw, { params });
    });
  }
  if ((route17 as any).PATCH) {
    api.patch('/videos/generate', async (c: any) => {
      const params = c.req.param();
      return await (route17 as any).PATCH(c.req.raw, { params });
    });
  }
  if ((route18 as any).GET) {
    api.get('/brand/generate', async (c: any) => {
      const params = c.req.param();
      return await (route18 as any).GET(c.req.raw, { params });
    });
  }
  if ((route18 as any).POST) {
    api.post('/brand/generate', async (c: any) => {
      const params = c.req.param();
      return await (route18 as any).POST(c.req.raw, { params });
    });
  }
  if ((route18 as any).PUT) {
    api.put('/brand/generate', async (c: any) => {
      const params = c.req.param();
      return await (route18 as any).PUT(c.req.raw, { params });
    });
  }
  if ((route18 as any).DELETE) {
    api.delete('/brand/generate', async (c: any) => {
      const params = c.req.param();
      return await (route18 as any).DELETE(c.req.raw, { params });
    });
  }
  if ((route18 as any).PATCH) {
    api.patch('/brand/generate', async (c: any) => {
      const params = c.req.param();
      return await (route18 as any).PATCH(c.req.raw, { params });
    });
  }
  if ((route19 as any).GET) {
    api.get('/campaigns/list', async (c: any) => {
      const params = c.req.param();
      return await (route19 as any).GET(c.req.raw, { params });
    });
  }
  if ((route19 as any).POST) {
    api.post('/campaigns/list', async (c: any) => {
      const params = c.req.param();
      return await (route19 as any).POST(c.req.raw, { params });
    });
  }
  if ((route19 as any).PUT) {
    api.put('/campaigns/list', async (c: any) => {
      const params = c.req.param();
      return await (route19 as any).PUT(c.req.raw, { params });
    });
  }
  if ((route19 as any).DELETE) {
    api.delete('/campaigns/list', async (c: any) => {
      const params = c.req.param();
      return await (route19 as any).DELETE(c.req.raw, { params });
    });
  }
  if ((route19 as any).PATCH) {
    api.patch('/campaigns/list', async (c: any) => {
      const params = c.req.param();
      return await (route19 as any).PATCH(c.req.raw, { params });
    });
  }
  if ((route20 as any).GET) {
    api.get('/content/delete', async (c: any) => {
      const params = c.req.param();
      return await (route20 as any).GET(c.req.raw, { params });
    });
  }
  if ((route20 as any).POST) {
    api.post('/content/delete', async (c: any) => {
      const params = c.req.param();
      return await (route20 as any).POST(c.req.raw, { params });
    });
  }
  if ((route20 as any).PUT) {
    api.put('/content/delete', async (c: any) => {
      const params = c.req.param();
      return await (route20 as any).PUT(c.req.raw, { params });
    });
  }
  if ((route20 as any).DELETE) {
    api.delete('/content/delete', async (c: any) => {
      const params = c.req.param();
      return await (route20 as any).DELETE(c.req.raw, { params });
    });
  }
  if ((route20 as any).PATCH) {
    api.patch('/content/delete', async (c: any) => {
      const params = c.req.param();
      return await (route20 as any).PATCH(c.req.raw, { params });
    });
  }
  if ((route21 as any).GET) {
    api.get('/creatives/list', async (c: any) => {
      const params = c.req.param();
      return await (route21 as any).GET(c.req.raw, { params });
    });
  }
  if ((route21 as any).POST) {
    api.post('/creatives/list', async (c: any) => {
      const params = c.req.param();
      return await (route21 as any).POST(c.req.raw, { params });
    });
  }
  if ((route21 as any).PUT) {
    api.put('/creatives/list', async (c: any) => {
      const params = c.req.param();
      return await (route21 as any).PUT(c.req.raw, { params });
    });
  }
  if ((route21 as any).DELETE) {
    api.delete('/creatives/list', async (c: any) => {
      const params = c.req.param();
      return await (route21 as any).DELETE(c.req.raw, { params });
    });
  }
  if ((route21 as any).PATCH) {
    api.patch('/creatives/list', async (c: any) => {
      const params = c.req.param();
      return await (route21 as any).PATCH(c.req.raw, { params });
    });
  }
  if ((route22 as any).GET) {
    api.get('/scrape/website', async (c: any) => {
      const params = c.req.param();
      return await (route22 as any).GET(c.req.raw, { params });
    });
  }
  if ((route22 as any).POST) {
    api.post('/scrape/website', async (c: any) => {
      const params = c.req.param();
      return await (route22 as any).POST(c.req.raw, { params });
    });
  }
  if ((route22 as any).PUT) {
    api.put('/scrape/website', async (c: any) => {
      const params = c.req.param();
      return await (route22 as any).PUT(c.req.raw, { params });
    });
  }
  if ((route22 as any).DELETE) {
    api.delete('/scrape/website', async (c: any) => {
      const params = c.req.param();
      return await (route22 as any).DELETE(c.req.raw, { params });
    });
  }
  if ((route22 as any).PATCH) {
    api.patch('/scrape/website', async (c: any) => {
      const params = c.req.param();
      return await (route22 as any).PATCH(c.req.raw, { params });
    });
  }
  if ((route23 as any).GET) {
    api.get('/videos/create', async (c: any) => {
      const params = c.req.param();
      return await (route23 as any).GET(c.req.raw, { params });
    });
  }
  if ((route23 as any).POST) {
    api.post('/videos/create', async (c: any) => {
      const params = c.req.param();
      return await (route23 as any).POST(c.req.raw, { params });
    });
  }
  if ((route23 as any).PUT) {
    api.put('/videos/create', async (c: any) => {
      const params = c.req.param();
      return await (route23 as any).PUT(c.req.raw, { params });
    });
  }
  if ((route23 as any).DELETE) {
    api.delete('/videos/create', async (c: any) => {
      const params = c.req.param();
      return await (route23 as any).DELETE(c.req.raw, { params });
    });
  }
  if ((route23 as any).PATCH) {
    api.patch('/videos/create', async (c: any) => {
      const params = c.req.param();
      return await (route23 as any).PATCH(c.req.raw, { params });
    });
  }
  if ((route24 as any).GET) {
    api.get('/videos/delete', async (c: any) => {
      const params = c.req.param();
      return await (route24 as any).GET(c.req.raw, { params });
    });
  }
  if ((route24 as any).POST) {
    api.post('/videos/delete', async (c: any) => {
      const params = c.req.param();
      return await (route24 as any).POST(c.req.raw, { params });
    });
  }
  if ((route24 as any).PUT) {
    api.put('/videos/delete', async (c: any) => {
      const params = c.req.param();
      return await (route24 as any).PUT(c.req.raw, { params });
    });
  }
  if ((route24 as any).DELETE) {
    api.delete('/videos/delete', async (c: any) => {
      const params = c.req.param();
      return await (route24 as any).DELETE(c.req.raw, { params });
    });
  }
  if ((route24 as any).PATCH) {
    api.patch('/videos/delete', async (c: any) => {
      const params = c.req.param();
      return await (route24 as any).PATCH(c.req.raw, { params });
    });
  }
  if ((route25 as any).GET) {
    api.get('/brand/delete', async (c: any) => {
      const params = c.req.param();
      return await (route25 as any).GET(c.req.raw, { params });
    });
  }
  if ((route25 as any).POST) {
    api.post('/brand/delete', async (c: any) => {
      const params = c.req.param();
      return await (route25 as any).POST(c.req.raw, { params });
    });
  }
  if ((route25 as any).PUT) {
    api.put('/brand/delete', async (c: any) => {
      const params = c.req.param();
      return await (route25 as any).PUT(c.req.raw, { params });
    });
  }
  if ((route25 as any).DELETE) {
    api.delete('/brand/delete', async (c: any) => {
      const params = c.req.param();
      return await (route25 as any).DELETE(c.req.raw, { params });
    });
  }
  if ((route25 as any).PATCH) {
    api.patch('/brand/delete', async (c: any) => {
      const params = c.req.param();
      return await (route25 as any).PATCH(c.req.raw, { params });
    });
  }
  if ((route26 as any).GET) {
    api.get('/content/list', async (c: any) => {
      const params = c.req.param();
      return await (route26 as any).GET(c.req.raw, { params });
    });
  }
  if ((route26 as any).POST) {
    api.post('/content/list', async (c: any) => {
      const params = c.req.param();
      return await (route26 as any).POST(c.req.raw, { params });
    });
  }
  if ((route26 as any).PUT) {
    api.put('/content/list', async (c: any) => {
      const params = c.req.param();
      return await (route26 as any).PUT(c.req.raw, { params });
    });
  }
  if ((route26 as any).DELETE) {
    api.delete('/content/list', async (c: any) => {
      const params = c.req.param();
      return await (route26 as any).DELETE(c.req.raw, { params });
    });
  }
  if ((route26 as any).PATCH) {
    api.patch('/content/list', async (c: any) => {
      const params = c.req.param();
      return await (route26 as any).PATCH(c.req.raw, { params });
    });
  }
  if ((route27 as any).GET) {
    api.get('/videos/list', async (c: any) => {
      const params = c.req.param();
      return await (route27 as any).GET(c.req.raw, { params });
    });
  }
  if ((route27 as any).POST) {
    api.post('/videos/list', async (c: any) => {
      const params = c.req.param();
      return await (route27 as any).POST(c.req.raw, { params });
    });
  }
  if ((route27 as any).PUT) {
    api.put('/videos/list', async (c: any) => {
      const params = c.req.param();
      return await (route27 as any).PUT(c.req.raw, { params });
    });
  }
  if ((route27 as any).DELETE) {
    api.delete('/videos/list', async (c: any) => {
      const params = c.req.param();
      return await (route27 as any).DELETE(c.req.raw, { params });
    });
  }
  if ((route27 as any).PATCH) {
    api.patch('/videos/list', async (c: any) => {
      const params = c.req.param();
      return await (route27 as any).PATCH(c.req.raw, { params });
    });
  }
  if ((route28 as any).GET) {
    api.get('/auth/token', async (c: any) => {
      const params = c.req.param();
      return await (route28 as any).GET(c.req.raw, { params });
    });
  }
  if ((route28 as any).POST) {
    api.post('/auth/token', async (c: any) => {
      const params = c.req.param();
      return await (route28 as any).POST(c.req.raw, { params });
    });
  }
  if ((route28 as any).PUT) {
    api.put('/auth/token', async (c: any) => {
      const params = c.req.param();
      return await (route28 as any).PUT(c.req.raw, { params });
    });
  }
  if ((route28 as any).DELETE) {
    api.delete('/auth/token', async (c: any) => {
      const params = c.req.param();
      return await (route28 as any).DELETE(c.req.raw, { params });
    });
  }
  if ((route28 as any).PATCH) {
    api.patch('/auth/token', async (c: any) => {
      const params = c.req.param();
      return await (route28 as any).PATCH(c.req.raw, { params });
    });
  }
  if ((route29 as any).GET) {
    api.get('/brand/get', async (c: any) => {
      const params = c.req.param();
      return await (route29 as any).GET(c.req.raw, { params });
    });
  }
  if ((route29 as any).POST) {
    api.post('/brand/get', async (c: any) => {
      const params = c.req.param();
      return await (route29 as any).POST(c.req.raw, { params });
    });
  }
  if ((route29 as any).PUT) {
    api.put('/brand/get', async (c: any) => {
      const params = c.req.param();
      return await (route29 as any).PUT(c.req.raw, { params });
    });
  }
  if ((route29 as any).DELETE) {
    api.delete('/brand/get', async (c: any) => {
      const params = c.req.param();
      return await (route29 as any).DELETE(c.req.raw, { params });
    });
  }
  if ((route29 as any).PATCH) {
    api.patch('/brand/get', async (c: any) => {
      const params = c.req.param();
      return await (route29 as any).PATCH(c.req.raw, { params });
    });
  }
}
